// <auto-generated />
namespace _Books.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddChangeCategoryName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddChangeCategoryName));
        
        string IMigrationMetadata.Id
        {
            get { return "202107031216102_AddChangeCategoryName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
